-- MySQL Script generated by MySQL Workbench
-- Thu Aug  3 00:07:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema st
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `st` ;

-- -----------------------------------------------------
-- Schema st
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `st` DEFAULT CHARACTER SET utf8 ;
USE `st` ;

-- -----------------------------------------------------
-- Table `st`.`parada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `st`.`parada` ;

CREATE TABLE IF NOT EXISTS `st`.`parada` (
  `id_parada` INT NOT NULL,
  `nombre_parada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_parada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`ruta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `st`.`ruta` ;

CREATE TABLE IF NOT EXISTS `st`.`ruta` (
  `id_ruta` INT NOT NULL,
  `id_parada_origen` INT NULL,
  `id_parada_destino` INT NULL,
  `distancia` FLOAT NULL,
  `via` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ruta`),
  INDEX `idCiudadOrigen_idx` (`id_parada_origen` ASC),
  INDEX `idCiudadDestino_idx` (`id_parada_destino` ASC),
  CONSTRAINT `id_parada_origen`
    FOREIGN KEY (`id_parada_origen`)
    REFERENCES `st`.`parada` (`id_parada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_parada_destino`
    FOREIGN KEY (`id_parada_destino`)
    REFERENCES `st`.`parada` (`id_parada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `st`.`event` ;

CREATE TABLE IF NOT EXISTS `st`.`event` (
  `id_event` INT NOT NULL,
  `lugar_event` INT NULL,
  `nombre_vent` VARCHAR(45) NULL,
  `grado_accidente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_event`),
  INDEX `lugarEvent_idx` (`lugar_event` ASC),
  CONSTRAINT `lugar_event`
    FOREIGN KEY (`lugar_event`)
    REFERENCES `st`.`parada` (`id_parada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `st`.`event_parada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `st`.`event_parada` ;

CREATE TABLE IF NOT EXISTS `st`.`event_parada` (
  `id_event_parada` INT NOT NULL,
  `id_event` INT NULL,
  `id_ruta` INT NULL,
  `estado` VARCHAR(45) NULL,
  `informe` VARCHAR(45) NULL,
  PRIMARY KEY (`id_event_parada`),
  INDEX `idEvent_idx` (`id_event` ASC),
  INDEX `id_ruta_idx` (`id_ruta` ASC),
  CONSTRAINT `id_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `st`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_ruta`
    FOREIGN KEY (`id_ruta`)
    REFERENCES `st`.`ruta` (`id_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `st`.`parada`
-- -----------------------------------------------------
START TRANSACTION;
USE `st`;
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (1, 'Guayaquil');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (2, 'Duran');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (3, 'Nobol');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (4, 'Chongon');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (5, 'Yaguachi');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (6, 'Virgen de Fatima');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (7, 'Milagro');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (8, 'El Triunfo');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (9, 'Naranjito');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (10, 'Cumanda');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (11, 'Pallatanga');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (12, 'Riobamba');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (13, 'Ambato');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (14, 'Babahoyo');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (15, 'Montalvo');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (16, 'Guaranda');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (17, 'Volcan Chimborazo');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (18, 'Latacunga');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (19, 'Machachi');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (20, 'Quito');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (21, 'Daule');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (22, 'Balzar');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (23, 'Quevedo');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (24, 'Santo Domingo de los Colorados');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (25, 'Pedro Carbo');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (26, 'Jipijapa');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (27, 'Portoviejo');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (28, 'Chone');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (29, 'El Carmen');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (30, 'Santa Elena');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (31, 'Montanita');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (32, 'Puerto Lopez');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (33, 'Machalilla');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (34, 'Manta');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (35, 'Bahia de Caraquez');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (36, 'Jama');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (37, 'Pedernales');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (38, 'Atacames');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (39, 'Esmeraldas');
INSERT INTO `st`.`parada` (`id_parada`, `nombre_parada`) VALUES (40, 'Concordia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `st`.`ruta`
-- -----------------------------------------------------
START TRANSACTION;
USE `st`;
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (1, 1, 2, 19, 'Punte de la Unidad Nacional');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (2, 1, 3, 33, 'Via Daule');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (3, 1, 4, 22, 'Via a la Costa');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (4, 2, 5, 22, 'Via E45');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (5, 2, 6, 24, 'Via E40');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (6, 5, 7, 15.5, 'Troncal de la Costa');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (7, 6, 7, 12.6, 'Troncal de la Costa');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (8, 6, 8, 30.4, 'Transversal Austral- E40');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (9, 7, 9, 18, 'Via Naranjito');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (10, 8, 10, 38.6, 'Via E487');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (11, 9, 10, 41.4, 'Autopista Naranjito Bucay');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (12, 10, 11, 38, 'Via E487');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (13, 11, 12, 87, 'Via E35');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (14, 12, 13, 53.5, 'Via E35 - E30');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (15, 5, 14, 41, 'Via E25');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (16, 14, 15, 32.6, 'Via Guaranda - Babahoyo E491');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (17, 15, 16, 62, 'Via Guaranda - Babahoyo E491');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (18, 16, 17, 33.5, 'Via Ambato - Guaranda E491');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (19, 17, 13, 65, 'Via Ambato - Guaranda E491');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (20, 13, 18, 44, 'Carretera Panamericana');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (21, 18, 19, 57, 'Carretera Panamericana');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (22, 19, 20, 50, 'Avenida Simon Bolivar');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (23, 3, 21, 10.5, 'Via a Duale');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (24, 21, 22, 63, 'Via E48');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (25, 22, 23, 75, 'Via E30');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (26, 23, 24, 101, 'Troncal de la Costa E25');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (27, 24, 19, 103, 'Via E20');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (28, 3, 25, 30, 'Via E482');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (29, 25, 26, 75, 'Via E482');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (30, 26, 27, 51, 'Via E482');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (31, 27, 28, 73, 'Via E384');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (32, 28, 29, 118, 'Via E38');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (33, 29, 24, 37, 'Via E382');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (34, 4, 30, 104, 'Via a la Costa');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (35, 30, 31, 57, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (36, 31, 32, 44, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (37, 32, 33, 12.6, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (38, 33, 34, 98, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (39, 34, 27, 48.5, 'Via Manta Portoviejo');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (40, 34, 35, 82, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (41, 35, 36, 66.5, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (42, 36, 37, 45, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (43, 37, 38, 156, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (44, 38, 39, 31, 'Ruta del Spondylus');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (45, 39, 40, 136, 'Via E28');
INSERT INTO `st`.`ruta` (`id_ruta`, `id_parada_origen`, `id_parada_destino`, `distancia`, `via`) VALUES (46, 40, 24, 42, 'Via E28');

COMMIT;


-- -----------------------------------------------------
-- Data for table `st`.`event`
-- -----------------------------------------------------
START TRANSACTION;
USE `st`;
INSERT INTO `st`.`event` (`id_event`, `lugar_event`, `nombre_vent`, `grado_accidente`) VALUES (1, 1, 'paro', '0.5');

COMMIT;


-- -----------------------------------------------------
-- Data for table `st`.`event_parada`
-- -----------------------------------------------------
START TRANSACTION;
USE `st`;
INSERT INTO `st`.`event_parada` (`id_event_parada`, `id_event`, `id_ruta`, `estado`, `informe`) VALUES (1, 1, 1, NULL, 'Los estudiantes salieron a las calles');

COMMIT;

